name: Build
description: Build Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "./src/main/docker/Dockerfile.jvm"
  image_name:
    description: "Image name"
    required: false
    default: "academy"
  tag_name:
    description: "Tag name"
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: Set tag name if empty
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          tag_name=$(date +%s)
        else
          tag_name=${{ inputs.tag_name }}
        fi
        echo "tag_name=$tag_name" >> $GITHUB_ENV
    - name: Create docker image
      shell: bash
      run:
        docker build . --file ${{inputs.dockerfile_path}} --tag ${{inputs.image_name}}:${{env.tag_name}}
    - name: List docker images
      run: docker image ls
      shell: bash
