name: Build
description: Build Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "./src/main/docker/Dockerfile.jvm"
  image_name:
    description: "Image name"
    required: false
    default: "academy"
  tag_name:
    description: "Tag name"
    required: false
    default: "$(date +%s)"
runs:
  using: composite
  steps:
    - name: Create docker image
      shell: bash
      run:
        docker build . --file ${{inputs.dockerfile_path}} --tag ${{inputs.image_name}}:${{inputs.tag_name}}
    - name: List docker images
      run: docker image ls
      shell: bash
