name: Build
description: Build application with Maven
runs:
  using: composite
  steps:
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      shell: bash

