name: Push
description: Push Docker image
inputs:
  image_name:
    description: "Image name"
    required: true
  tag_name:
    description: "Tag name"
    required: true
  dockerhub_repo:
    description: "Docker Hub repository"
    required: true
runs:
  using: composite
  steps:
    - name: Tag docker image for Docker Hub
      shell: bash
      run: |
        docker tag ${{inputs.image_name}}:${{inputs.tag_name}} ${{inputs.dockerhub_repo}}

    - name: Push docker image to Docker Hub
      shell: bash
      run: |
        docker push ${{inputs.dockerhub_repo}}

    - name: List docker images
      run: docker image ls
      shell: bash
