name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven build
        uses: JKz02/academy/.github/actions/maven_build@main

      - name: Build docker image
        id: docker_build
        uses: JKz02/academy/.github/actions/docker_build@main
        with:
          tag_name: 'coolest_image'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker image push
        uses: JKz02/academy/.github/actions/docker_image_push@main
        with:
          image_name: "academy"
          tag_name: ${{env.tag_name}}
          dockerhub_repo: 'andrefilipealmeida478/github-actions'
