name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fs_academy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven build
        uses: JKz02/academy/.github/actions/maven_build@main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        id: docker_build
        uses: JKz02/academy/.github/actions/docker_build@main

      - name: Docker image push
        uses: JKz02/academy/.github/actions/docker_image_push@main
        with:
          image_name: "academy"
          tag_name: ${{env.tag_name}}
          dockerhub_repo: 'andrefilipealmeida478/github-actions'
          c
      - name: Run tests
        shell: bash
        run: mvn test
